language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  
notifications:
  email: false

install:
  - pip install --user -r requirements.txt
  - python setup.py install

script:
  - python setup.py develop test
